#!/bin/bash
# Pins AutoEQParser — turning a downloaded AutoEQ text profile into filters.
#
# Untested until now, and the failure mode is silent: a mis-parsed line does not
# error, it applies the WRONG equalisation to the user's audio. A dropped minus
# sign turns a -6 dB cut into a +6 dB boost; a missed "OFF" applies a filter the
# profile author disabled; a bad Q makes a gentle shelf into a resonant peak.
# None of that surfaces as anything except "this sounds off".
#
# Fixtures are real oratory1990-format lines, which is the format the fetcher
# actually downloads.
set -euo pipefail
cd "$(dirname "$0")/.."

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

python3 - "$WORK/Parser.swift" <<'PYX'
import re, sys
model = open("Anchor/Audio/PerApp/Models/AutoEQProfile.swift").read()
parser = open("Anchor/Audio/PerApp/AutoEQ/AutoEQParser.swift").read()

def block(src, pattern):
    m = re.search(pattern, src)
    i = m.start()
    depth, k = 0, src.index("{", i)
    while True:
        if src[k] == "{": depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0: break
        k += 1
    return src[i:k+1]

out = ["import Foundation\n"]
out.append(block(model,  r'struct AutoEQFilter\b'))
out.append(block(model,  r'enum AutoEQSource\b'))
out.append(block(model,  r'struct AutoEQProfile\b'))
out.append(block(parser, r'enum AutoEQParser\b'))
src = "\n\n".join(out)
src = re.sub(r'^\s*import (os|OSLog).*$', '', src, flags=re.M)
# CLAUDE.md: Anchor declares its own `Logger`, so every ported FineTune file
# spells out `os.Logger(...)`. A no-op shim keeps that call site compiling
# standalone without touching the source under test.
shim = """
enum os {
    struct Logger {
        init(subsystem: String = "", category: String = "") {}
        func debug(_ m: String) {}
        func info(_ m: String) {}
        func error(_ m: String) {}
        func warning(_ m: String) {}
        func notice(_ m: String) {}
    }
}
"""
open(sys.argv[1], "w").write("import Foundation\n" + shim + src.replace("import Foundation", "", 1) + "\n")
PYX

cat > "$WORK/main.swift" <<'SWIFT'
import Foundation

var passes = 0, failures = 0
func ok(_ label: String, _ c: Bool, _ d: String = "") {
    if c { passes += 1 } else { failures += 1; print("  FAIL \(label)\(d.isEmpty ? "" : ": \(d)")") }
}
func parse(_ t: String) -> AutoEQProfile? {
    AutoEQParser.parse(text: t, name: "Test", source: .imported)
}

// ---------- a real oratory1990 profile ----------
let real = """
Preamp: -6.2 dB
Filter 1: ON PK Fc 105 Hz Gain -2.3 dB Q 0.70
Filter 2: ON PK Fc 1100 Hz Gain 1.8 dB Q 1.41
Filter 3: ON LSC Fc 105 Hz Gain 7.0 dB Q 0.71
Filter 4: ON HSC Fc 10000 Hz Gain -3.5 dB Q 0.71
"""
guard let p = parse(real) else { fatalError("real profile failed to parse") }
ok("parses four filters", p.filters.count == 4, "got \(p.filters.count)")
ok("preamp is negative and exact", abs(p.preampDB - (-6.2)) < 0.001, "got \(p.preampDB)")
ok("first is peaking",    p.filters[0].type == .peaking)
ok("third is low shelf",  p.filters[2].type == .lowShelf)
ok("fourth is high shelf",p.filters[3].type == .highShelf)
ok("frequency parsed",    p.filters[0].frequency == 105, "got \(p.filters[0].frequency)")
ok("Q parsed",            abs(p.filters[0].q - 0.70) < 0.001, "got \(p.filters[0].q)")

// THE sign test. A dropped minus turns a cut into a boost — inaudible as a bug,
// very audible as a result.
ok("negative gain stays negative", p.filters[0].gainDB < 0, "got \(p.filters[0].gainDB)")
ok("negative gain is exact", abs(p.filters[0].gainDB - (-2.3)) < 0.001, "got \(p.filters[0].gainDB)")
ok("positive gain stays positive", p.filters[1].gainDB > 0, "got \(p.filters[1].gainDB)")
ok("high shelf cut stays a cut", p.filters[3].gainDB < 0, "got \(p.filters[3].gainDB)")

// ---------- OFF filters must be skipped ----------
let withOff = """
Filter 1: ON PK Fc 100 Hz Gain 3.0 dB Q 1.0
Filter 2: OFF PK Fc 200 Hz Gain 9.0 dB Q 1.0
Filter 3: ON PK Fc 300 Hz Gain 1.0 dB Q 1.0
"""
if let o = parse(withOff) {
    ok("disabled filter is skipped", o.filters.count == 2, "got \(o.filters.count)")
    ok("the skipped one is not present",
       !o.filters.contains { $0.frequency == 200 },
       "frequencies \(o.filters.map(\.frequency))")
} else { failures += 1; print("  FAIL withOff did not parse") }

// ---------- comments, blank lines, irregular whitespace ----------
let messy = """
# AutoEQ profile for Something
# generated by oratory1990

Preamp:   -3.1   dB

Filter  1:  ON  PK  Fc  1000  Hz  Gain  2.5  dB  Q  1.41

"""
if let m = parse(messy) {
    ok("comments and blank lines ignored", m.filters.count == 1)
    ok("irregular whitespace in preamp", abs(m.preampDB - (-3.1)) < 0.001, "got \(m.preampDB)")
    ok("irregular whitespace in filter", m.filters[0].frequency == 1000)
} else { failures += 1; print("  FAIL messy did not parse") }

// ---------- rejection ----------
ok("empty text yields nil",            parse("") == nil)
ok("comments only yields nil",         parse("# nothing here\n# at all") == nil)
ok("preamp with no filters yields nil", parse("Preamp: -5.0 dB") == nil)
ok("garbage yields nil",               parse("this is not a profile") == nil)
ok("all-OFF yields nil",               parse("Filter 1: OFF PK Fc 100 Hz Gain 3 dB Q 1") == nil)

// ---------- limits ----------
var many = ""
for i in 1...25 { many += "Filter \(i): ON PK Fc \(100 * i) Hz Gain 1.0 dB Q 1.0\n" }
if let big = parse(many) {
    ok("filter count is capped at maxFilters",
       big.filters.count == AutoEQProfile.maxFilters, "got \(big.filters.count)")
    ok("the cap keeps the FIRST filters, not a random slice",
       big.filters[0].frequency == 100)
} else { failures += 1; print("  FAIL many did not parse") }

// Preamp is clamped — a corrupt profile must not apply +200 dB.
for (text, want) in [("Preamp: 200 dB", Float(30)), ("Preamp: -200 dB", Float(-30))] {
    if let c = parse(text + "\nFilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1") {
        ok("preamp clamped for \"\(text)\"", c.preampDB == want, "got \(c.preampDB)")
    } else { failures += 1; print("  FAIL clamp case did not parse") }
}
ok("non-numeric preamp defaults to 0",
   parse("Preamp: abc dB\nFilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1")?.preampDB == 0)
ok("missing preamp defaults to 0",
   parse("Filter 1: ON PK Fc 100 Hz Gain 1 dB Q 1")?.preampDB == 0)

// ---------- case insensitivity ----------
ok("lowercase preamp key",
   parse("preamp: -2.0 dB\nfilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1") != nil)
if let lc = parse("preamp: -2.0 dB\nfilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1") {
    ok("lowercase preamp value read", abs(lc.preampDB - (-2.0)) < 0.001, "got \(lc.preampDB)")
}

// ---------- every parsed filter must be usable ----------
if let p2 = parse(real) {
    var bad: [String] = []
    for f in p2.filters {
        if !(f.frequency > 0 && f.frequency < 24_000) { bad.append("freq \(f.frequency)") }
        if !(f.q > 0 && f.q < 100)                    { bad.append("q \(f.q)") }
        if !f.gainDB.isFinite || abs(f.gainDB) > 40   { bad.append("gain \(f.gainDB)") }
    }
    ok("every filter has usable values", bad.isEmpty, "\(bad)")
}

if failures == 0 { print("\(passes)/\(passes) passed"); exit(0) }
print("\(passes) passed, \(failures) failed"); exit(1)
SWIFT

swiftc -O "$WORK/Parser.swift" "$WORK/main.swift" -o "$WORK/aeq" 2>&1 | grep -E "error" || true
"$WORK/aeq"
